// <auto-generated />
namespace AppTorneos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class id_empresaenusuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(id_empresaenusuario));
        
        string IMigrationMetadata.Id
        {
            get { return "202001172127059_id_empresa-enusuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
