// <auto-generated />
namespace AppTorneos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class id_usuario_en_empresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(id_usuario_en_empresa));
        
        string IMigrationMetadata.Id
        {
            get { return "202001171737182_id_usuario_en_empresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
