// <auto-generated />
namespace AppTorneos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stringaintid_partido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stringaintid_partido));
        
        string IMigrationMetadata.Id
        {
            get { return "202001211815514_string-a-int-id_partido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
