// <auto-generated />
namespace AppTorneos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class torneo_partido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(torneo_partido));
        
        string IMigrationMetadata.Id
        {
            get { return "202001201456218_torneo_partido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
